import 'dart:typed_data';

import '../byte_writer.dart';
import '../encoding.dart';
import '../languages/cpcl_writer.dart';
import '../types.dart';
import 'cpcl_types.dart';

/// Protocol-native fluent command-stream builder for Comtec / Zebra CPCL mobile printers.
///
/// Accumulates CPCL commands in deliberate sequential order and emits byte-exact
/// [Uint8List] payloads via [toBytes].
///
/// This builder does NOT manage network, Bluetooth, or USB sockets; generated bytes
/// should be passed to a transport layer.
class CpclPrinter {
  final CpclEncoding _initialEncoding;
  late CpclEncoding _activeEncoding;
  late CodePageEncoder _encoder;
  PrinterByteWriter _writer = PrinterByteWriter();

  /// Creates a new [CpclPrinter] with the specified default [encoding] (defaults to legacy CP437).
  CpclPrinter({CpclEncoding encoding = const CpclEncoding.legacy()})
    : _initialEncoding = encoding {
    _applyEncoding(encoding, emitCommand: encoding.sendCountryCommand);
  }

  void _applyEncoding(CpclEncoding enc, {required bool emitCommand}) {
    _activeEncoding = enc;
    _encoder = getEncoder(enc.codePage);
    if (emitCommand && enc.country != null) {
      CpclCommandWriter.writeCountry(_writer, enc.country!);
    }
  }

  /// Sets the active text [encoding] for subsequent commands and optionally emits `COUNTRY`.
  CpclPrinter encoding(CpclEncoding encoding) {
    _applyEncoding(encoding, emitCommand: encoding.sendCountryCommand);
    return this;
  }

  /// Emits CPCL session header: `! <offset> <hDpi> <vDpi> <heightDots> <copies>\r\n`.
  CpclPrinter startPage({
    int offset = 0,
    int hDpi = 203,
    int vDpi = 203,
    required int heightDots,
    int copies = 1,
  }) {
    CpclCommandWriter.writeHeader(
      _writer,
      offset: offset,
      hDpi: hDpi,
      vDpi: vDpi,
      heightDots: heightDots,
      copies: copies,
    );
    return this;
  }

  /// Emits `PAGE-WIDTH <widthDots>\r\n` — Page Width Setup.
  CpclPrinter pageWidth(int widthDots) {
    CpclCommandWriter.writePageWidth(_writer, widthDots);
    return this;
  }

  /// Emits `SPEED <level>\r\n` — Print Speed (0..5).
  CpclPrinter speed(int speed) {
    CpclCommandWriter.writeSpeed(_writer, speed);
    return this;
  }

  /// Emits `TONE <level>\r\n` — Print Density / Tone.
  CpclPrinter tone(int tone) {
    CpclCommandWriter.writeTone(_writer, tone);
    return this;
  }

  /// Emits `COUNTRY <country>\r\n` — Character Set Selection.
  CpclPrinter country(String country) {
    CpclCommandWriter.writeCountry(_writer, country);
    return this;
  }

  /// Emits `SETMAG <w> <h>\r\n` — Text Magnification (1..16).
  CpclPrinter setMag(int w, int h) {
    CpclCommandWriter.writeSetMag(_writer, w, h);
    return this;
  }

  /// Emits a text field (`<TEXT[rot]> <font> <size> <x> <y>\r\n<text>\r\n`).
  CpclPrinter text({
    required int x,
    required int y,
    required String text,
    String font = '2',
    int size = 0,
    CpclRotation rotation = CpclRotation.unrotated,
  }) {
    CpclCommandWriter.writeText(
      _writer,
      x: x,
      y: y,
      font: font,
      size: size,
      rotation: rotation.degrees,
      text: text,
      encoder: _encoder,
      replaceUnsupported: _activeEncoding.replaceUnsupported,
    );
    return this;
  }

  /// Emits a 1D barcode (`BARCODE <type> <width> <ratio> <height> <x> <y> <content>\r\n`).
  CpclPrinter barcode({
    required int x,
    required int y,
    required String content,
    CpclBarcodeType type = CpclBarcodeType.code128,
    int height = 50,
    int narrowBarWidth = 1,
    int wideRatio = 2,
    bool humanReadable = false,
  }) {
    CpclCommandWriter.writeBarcode(
      _writer,
      x: x,
      y: y,
      typeCode: type.code,
      narrowBarWidth: narrowBarWidth,
      wideRatio: wideRatio,
      height: height,
      humanReadable: humanReadable,
      content: content,
    );
    return this;
  }

  /// Emits a 2D QR Code (`BARCODE QR <x> <y> M 2 U <cw>\r\nMA,<content>\r\nENDQR\r\n`).
  CpclPrinter qrCode({
    required int x,
    required int y,
    required String content,
    int cellWidth = 4,
  }) {
    CpclCommandWriter.writeQrCode(
      _writer,
      x: x,
      y: y,
      cellWidth: cellWidth,
      content: content,
      encoder: _encoder,
      replaceUnsupported: _activeEncoding.replaceUnsupported,
    );
    return this;
  }

  /// Emits a box rectangle (`BOX <x1> <y1> <x2> <y2> <thickness>\r\n`).
  CpclPrinter box({
    required int x,
    required int y,
    required int width,
    required int height,
    int thickness = 1,
  }) {
    CpclCommandWriter.writeBox(
      _writer,
      x: x,
      y: y,
      width: width,
      height: height,
      thickness: thickness,
    );
    return this;
  }

  /// Emits a line segment (`LINE <x1> <y1> <x2> <y2> <thickness>\r\n`).
  CpclPrinter line({
    required int x1,
    required int y1,
    required int x2,
    required int y2,
    int thickness = 1,
  }) {
    CpclCommandWriter.writeLine(
      _writer,
      x1: x1,
      y1: y1,
      x2: x2,
      y2: y2,
      thickness: thickness,
    );
    return this;
  }

  /// Emits expanded graphics (`EG <bytesPerRow> <height> <x> <y> <hexData>\r\n`).
  CpclPrinter graphic({
    required int x,
    required int y,
    required Uint8List data,
    required int bytesPerRow,
    required int height,
  }) {
    CpclCommandWriter.writeExpandedGraphic(
      _writer,
      x: x,
      y: y,
      bytesPerRow: bytesPerRow,
      height: height,
      data: data,
    );
    return this;
  }

  /// Convenience helper to emit a [MonochromeBitmap] graphic.
  CpclPrinter graphicFromMonochrome(
    MonochromeBitmap bitmap, {
    required int x,
    required int y,
  }) {
    return graphic(
      x: x,
      y: y,
      data: bitmap.data,
      bytesPerRow: bitmap.bytesPerRow,
      height: bitmap.height,
    );
  }

  /// Emits `FORM\r\n` — Advance to next form.
  CpclPrinter form() {
    CpclCommandWriter.writeForm(_writer);
    return this;
  }

  /// Emits `PRINT\r\n` — Print Page.
  CpclPrinter print() {
    CpclCommandWriter.writePrint(_writer);
    return this;
  }

  /// Appends raw binary bytes directly to the command stream without alteration.
  CpclPrinter rawBytes(Uint8List bytes) {
    CpclCommandWriter.writeRawBytes(_writer, bytes);
    return this;
  }

  /// Appends a raw ASCII command string directly to the command stream.
  CpclPrinter rawAscii(String command, {bool appendNewline = false}) {
    CpclCommandWriter.writeRawAscii(
      _writer,
      command,
      appendNewline: appendNewline,
    );
    return this;
  }

  /// Returns a snapshot of the current binary command stream as [Uint8List].
  ///
  /// This method is idempotent and does NOT reset or mutate the builder.
  Uint8List toBytes() => _writer.toBytes();

  /// Clears all accumulated commands and restores encoding to constructor defaults.
  void reset() {
    _writer = PrinterByteWriter();
    _applyEncoding(_initialEncoding, emitCommand: false);
  }
}
