import 'dart:typed_data';

import '../byte_writer.dart';
import '../encoding.dart';
import '../languages/epl_writer.dart';
import '../types.dart';
import 'epl_types.dart';

/// Protocol-native fluent command-stream builder for Eltron EPL2 label printers.
///
/// Accumulates EPL2 commands in deliberate sequential order and emits byte-exact
/// [Uint8List] payloads via [toBytes].
///
/// This builder does NOT manage network, Bluetooth, or USB sockets; generated bytes
/// should be passed to a transport layer.
class EplPrinter {
  final EplEncoding _initialEncoding;
  late EplEncoding _activeEncoding;
  late CodePageEncoder _encoder;
  PrinterByteWriter _writer = PrinterByteWriter();

  /// Creates a new [EplPrinter] with the specified default [encoding] (defaults to legacy CP437).
  EplPrinter({EplEncoding encoding = const EplEncoding.legacy()})
      : _initialEncoding = encoding {
    _applyEncoding(encoding, emitCommand: encoding.sendSetCharSetCommand);
  }

  void _applyEncoding(EplEncoding enc, {required bool emitCommand}) {
    _activeEncoding = enc;
    _encoder = getEncoder(enc.codePage);
    if (emitCommand && enc.countryCode != null) {
      EplCommandWriter.writeCharSet(_writer, enc.countryCode!);
    }
  }

  /// Sets the active text [encoding] for subsequent commands and optionally emits `I8`.
  EplPrinter encoding(EplEncoding encoding) {
    _applyEncoding(encoding, emitCommand: encoding.sendSetCharSetCommand);
    return this;
  }

  /// Emits `N\n` to clear the printer's image buffer memory for a new label.
  EplPrinter clear() {
    EplCommandWriter.writeClear(_writer);
    return this;
  }

  /// Sets label width in dots (`q<widthDots>\n`).
  EplPrinter labelWidth(int widthDots) {
    EplCommandWriter.writeLabelWidth(_writer, widthDots);
    return this;
  }

  /// Sets label form length and gap offset in dots (`Q<heightDots>,<gapDots>\n`).
  EplPrinter labelLength(int heightDots, {int gapDots = 24}) {
    EplCommandWriter.writeLabelLength(_writer, heightDots, gapDots: gapDots);
    return this;
  }

  /// Sets print speed (1..6) (`S<speed>\n`).
  EplPrinter speed(int speed) {
    EplCommandWriter.writeSpeed(_writer, speed);
    return this;
  }

  /// Sets print density / darkness (0..15) (`D<density>\n`).
  EplPrinter density(int density) {
    EplCommandWriter.writeDensity(_writer, density);
    return this;
  }

  /// Sets label reference point offset in dots (`R<x>,<y>\n`).
  EplPrinter referencePoint(int x, int y) {
    EplCommandWriter.writeReferencePoint(_writer, x, y);
    return this;
  }

  /// Emits a text field (`A<x>,<y>,<rot>,<font>,<xMul>,<yMul>,<rev>,"<text>"\n`).
  EplPrinter text({
    required int x,
    required int y,
    required String text,
    EplFont font = EplFont.font2,
    EplRotation rotation = EplRotation.unrotated,
    int xMultiplier = 1,
    int yMultiplier = 1,
    bool reverse = false,
  }) {
    EplCommandWriter.writeText(
      _writer,
      x: x,
      y: y,
      rotation: rotation.value,
      font: font.code,
      xMultiplier: xMultiplier,
      yMultiplier: yMultiplier,
      reverse: reverse,
      text: text,
      encoder: _encoder,
      replaceUnsupported: _activeEncoding.replaceUnsupported,
    );
    return this;
  }

  /// Emits a 1D barcode (`B<x>,<y>,<rot>,<type>,<narrow>,<wide>,<height>,<hr>,"<content>"\n`).
  EplPrinter barcode({
    required int x,
    required int y,
    required String content,
    EplBarcodeType type = EplBarcodeType.code128,
    int height = 50,
    int narrowBarWidth = 2,
    int wideBarWidth = 4,
    bool humanReadable = false,
    EplRotation rotation = EplRotation.unrotated,
  }) {
    EplCommandWriter.writeBarcode(
      _writer,
      x: x,
      y: y,
      rotation: rotation.value,
      typeCode: type.code,
      narrowBarWidth: narrowBarWidth,
      wideBarWidth: wideBarWidth,
      height: height,
      humanReadable: humanReadable,
      content: content,
    );
    return this;
  }

  /// Emits a 2D QR Code (`b<x>,<y>,"Q",m2,s<cw>,e<ecc>,"<content>"\n`).
  EplPrinter qrCode({
    required int x,
    required int y,
    required String content,
    int cellWidth = 4,
    EplQrEcc ecc = EplQrEcc.q,
  }) {
    EplCommandWriter.writeQrCode(
      _writer,
      x: x,
      y: y,
      cellWidth: cellWidth,
      eccCode: ecc.code,
      content: content,
      encoder: _encoder,
      replaceUnsupported: _activeEncoding.replaceUnsupported,
    );
    return this;
  }

  /// Emits a box rectangle (`X<x1>,<y1>,<x2>,<y2>,<thickness>\n`).
  EplPrinter box({
    required int x,
    required int y,
    required int width,
    required int height,
    int thickness = 1,
  }) {
    EplCommandWriter.writeBox(
      _writer,
      x: x,
      y: y,
      width: width,
      height: height,
      thickness: thickness,
    );
    return this;
  }

  /// Emits an orthogonal black line segment.
  EplPrinter line({
    required int x1,
    required int y1,
    required int x2,
    required int y2,
    int thickness = 1,
  }) {
    if (y1 == y2) {
      final x = x1 < x2 ? x1 : x2;
      final w = (x2 - x1).abs();
      return lineDraw(x: x, y: y1, width: w == 0 ? 1 : w, height: thickness);
    } else if (x1 == x2) {
      final y = y1 < y2 ? y1 : y2;
      final h = (y2 - y1).abs();
      return lineDraw(x: x1, y: y, width: thickness, height: h == 0 ? 1 : h);
    } else {
      final x = x1 < x2 ? x1 : x2;
      final y = y1 < y2 ? y1 : y2;
      final w = (x2 - x1).abs();
      final h = (y2 - y1).abs();
      return lineDraw(
        x: x,
        y: y,
        width: w == 0 ? 1 : w,
        height: h == 0 ? 1 : h,
      );
    }
  }

  /// Emits a black line or filled rectangle (`LO<x>,<y>,<width>,<height>\n`).
  EplPrinter lineDraw({
    required int x,
    required int y,
    required int width,
    required int height,
  }) {
    EplCommandWriter.writeLine(
      _writer,
      x: x,
      y: y,
      width: width,
      height: height,
    );
    return this;
  }

  /// Emits a white line or erase rectangle (`LW<x>,<y>,<width>,<height>\n`).
  EplPrinter erase({
    required int x,
    required int y,
    required int width,
    required int height,
  }) {
    EplCommandWriter.writeWhiteLine(
      _writer,
      x: x,
      y: y,
      width: width,
      height: height,
    );
    return this;
  }

  /// Emits a 1-bit raster bit image (`GW<x>,<y>,<bytesPerRow>,<height>\n<binary data>\n`).
  ///
  /// In EPL2 `GW`, bit polarity is 0=black, 1=white. When [invert] is `true` (standard for
  /// 1-bit monochrome raster data where 1=black), bits are bitwise inverted before transmission.
  EplPrinter graphic({
    required int x,
    required int y,
    required Uint8List data,
    required int bytesPerRow,
    required int height,
    bool invert = true,
  }) {
    EplCommandWriter.writeGraphic(
      _writer,
      x: x,
      y: y,
      bytesPerRow: bytesPerRow,
      height: height,
      data: data,
      invert: invert,
    );
    return this;
  }

  /// Convenience helper to emit a [MonochromeBitmap] graphic.
  EplPrinter graphicFromMonochrome(
    MonochromeBitmap bitmap, {
    required int x,
    required int y,
    bool invert = true,
  }) {
    return graphic(
      x: x,
      y: y,
      data: bitmap.data,
      bytesPerRow: bitmap.bytesPerRow,
      height: bitmap.height,
      invert: invert,
    );
  }

  /// Emits label print execution command (`P<sets>[,<copies>]\n`).
  EplPrinter print({int sets = 1, int copies = 1}) {
    EplCommandWriter.writePrint(_writer, sets: sets, copies: copies);
    return this;
  }

  /// Activates the paper cutter (`C\n`).
  EplPrinter cut() {
    EplCommandWriter.writeCut(_writer);
    return this;
  }

  /// Appends raw binary bytes directly to the command stream without alteration.
  EplPrinter rawBytes(Uint8List bytes) {
    EplCommandWriter.writeRawBytes(_writer, bytes);
    return this;
  }

  /// Appends a raw ASCII command string directly to the command stream.
  EplPrinter rawAscii(String command, {bool appendNewline = false}) {
    EplCommandWriter.writeRawAscii(
      _writer,
      command,
      appendNewline: appendNewline,
    );
    return this;
  }

  /// Returns a snapshot of the current binary command stream as [Uint8List].
  ///
  /// This method is idempotent and does NOT reset or mutate the builder.
  Uint8List toBytes() => _writer.toBytes();

  /// Clears all accumulated commands and restores encoding to constructor defaults.
  void reset() {
    _writer = PrinterByteWriter();
    _applyEncoding(_initialEncoding, emitCommand: false);
  }
}
