import 'dart:convert';
import 'dart:typed_data';

import '../byte_writer.dart';
import '../encoding.dart';
import '../languages/escpos_writer.dart';
import '../types.dart';
import 'escpos_types.dart';

/// Protocol-native fluent command-stream builder for ESC/POS thermal receipt printers.
///
/// Accumulates ESC/POS binary command sequences in deliberate sequential order and emits
/// byte-exact [Uint8List] payloads via [toBytes].
///
/// This builder does NOT manage network, Bluetooth, or USB sockets; generated bytes
/// should be passed to a transport layer.
class EscPosPrinter {
  final EscPosEncoding _initialEncoding;
  late EscPosEncoding _activeEncoding;
  late CodePageEncoder _encoder;
  PrinterByteWriter _writer = PrinterByteWriter();

  /// Creates a new [EscPosPrinter] with the specified default [encoding] (defaults to CP437).
  ///
  /// If the configured [encoding] specifies `sendTableSelect: true` and `tableId != null`,
  /// an initial `ESC t <tableId>` command is emitted into the buffer.
  EscPosPrinter({EscPosEncoding encoding = const EscPosEncoding.cp437()})
      : _initialEncoding = encoding {
    _applyEncoding(encoding, emitCommand: encoding.sendTableSelect);
  }

  void _applyEncoding(EscPosEncoding encoding, {required bool emitCommand}) {
    _activeEncoding = encoding;
    _encoder = getEncoder(encoding.codePage);
    if (emitCommand && encoding.tableId != null) {
      EscPosCommandWriter.writeCodePage(_writer, encoding.tableId!);
    }
  }

  /// Changes the active text encoding and emits `ESC t <tableId>` if configured.
  EscPosPrinter encoding(EscPosEncoding encoding) {
    _applyEncoding(encoding, emitCommand: encoding.sendTableSelect);
    return this;
  }

  /// Explicitly emits `ESC t <tableId>` without altering the host character mapper.
  EscPosPrinter characterTable(int tableId) {
    EscPosCommandWriter.writeCodePage(_writer, tableId);
    return this;
  }

  /// Initializes the printer (`ESC @`), resetting internal printer hardware state.
  ///
  /// If the active encoding has `sendTableSelect: true` and `tableId != null`,
  /// re-emits `ESC t <tableId>` immediately following `ESC @`.
  EscPosPrinter initialize() {
    EscPosCommandWriter.writeInitialize(_writer);
    if (_activeEncoding.sendTableSelect && _activeEncoding.tableId != null) {
      EscPosCommandWriter.writeCodePage(_writer, _activeEncoding.tableId!);
    }
    return this;
  }

  /// Appends [text] using the active encoding without a line feed.
  EscPosPrinter text(String text) {
    if (text.isEmpty) return this;
    final bytes = _encoder.encode(
      text,
      replaceUnsupported: _activeEncoding.replaceUnsupported,
    );
    _writer.writeBytes(bytes);
    return this;
  }

  /// Appends [text] followed by a line feed (`0x0A`).
  EscPosPrinter textLine([String text = '']) {
    if (text.isNotEmpty) {
      final bytes = _encoder.encode(
        text,
        replaceUnsupported: _activeEncoding.replaceUnsupported,
      );
      _writer.writeBytes(bytes);
    }
    EscPosCommandWriter.writeLineFeed(_writer);
    return this;
  }

  /// Emits [lines] line feed (`0x0A`) characters.
  EscPosPrinter lineFeed([int lines = 1]) {
    EscPosCommandWriter.writeLineFeed(_writer, lines);
    return this;
  }

  /// Feeds paper by [lines] lines (`ESC d <lines>`).
  EscPosPrinter feedLines(int lines) {
    EscPosCommandWriter.writeFeedLines(_writer, lines);
    return this;
  }

  /// Feeds paper by [dots] vertical dots (`ESC J <dots>`).
  EscPosPrinter feedDots(int dots) {
    EscPosCommandWriter.writeFeedDots(_writer, dots);
    return this;
  }

  /// Sets text justification on the page roll (`ESC a <n>`).
  EscPosPrinter align(EscPosAlignment alignment) {
    EscPosCommandWriter.writeAlign(_writer, alignment.value);
    return this;
  }

  /// Enables or disables emphasized (bold) text mode (`ESC E <n>`).
  EscPosPrinter bold([bool enabled = true]) {
    EscPosCommandWriter.writeBold(_writer, enabled);
    return this;
  }

  /// Configures text underline mode (`ESC - <n>`).
  EscPosPrinter underline([EscPosUnderline mode = EscPosUnderline.single]) {
    EscPosCommandWriter.writeUnderline(_writer, mode.value);
    return this;
  }

  /// Enables or disables white-on-black reverse printing mode (`GS B <n>`).
  EscPosPrinter invert([bool enabled = true]) {
    EscPosCommandWriter.writeInvert(_writer, enabled);
    return this;
  }

  /// Selects the resident character font (`ESC M <n>`).
  ///
  /// Note: Font C availability is printer-model dependent.
  EscPosPrinter font(EscPosFont font) {
    EscPosCommandWriter.writeFont(_writer, font.value);
    return this;
  }

  /// Sets character size scaling multipliers (`GS ! <n>`).
  ///
  /// [width] and [height] must be between 1 and 8 (1x to 8x magnification).
  EscPosPrinter textSize({int width = 1, int height = 1}) {
    EscPosCommandWriter.writeTextSize(_writer, width: width, height: height);
    return this;
  }

  /// Emits a 1D barcode (`GS k` Function B).
  EscPosPrinter barcode({
    required String content,
    required EscPosBarcodeType type,
    int height = 64,
    int width = 3,
    EscPosBarcodeHri hri = EscPosBarcodeHri.none,
    EscPosBarcodeFont hriFont = EscPosBarcodeFont.fontA,
  }) {
    final barcodeBytes = ascii.encode(content);
    EscPosCommandWriter.writeBarcode(
      _writer,
      type: type.value,
      height: height,
      width: width,
      hri: hri.value,
      hriFont: hriFont.value,
      content: barcodeBytes,
    );
    return this;
  }

  /// Emits a 2D QR Code using the standard 5-step `GS ( k` lifecycle.
  ///
  /// [size] specifies module dot size (1..16). Note that some compact printer models
  /// support narrower hardware ranges (e.g. 1..8).
  EscPosPrinter qrCode(
    String content, {
    int size = 4,
    EscPosQrEcc ecc = EscPosQrEcc.m,
    EscPosQrModel model = EscPosQrModel.model2,
  }) {
    final contentBytes = utf8.encode(content);
    EscPosCommandWriter.writeQrCode(
      _writer,
      model: model.value,
      size: size,
      ecc: ecc.value,
      content: contentBytes,
    );
    return this;
  }

  /// Emits a 1-bit raster bit image (`GS v 0`).
  ///
  /// [data] must contain exactly [bytesPerRow] * [height] bytes. High bytes (0x00..0xFF)
  /// are preserved without alteration.
  EscPosPrinter raster({
    required Uint8List data,
    required int bytesPerRow,
    required int height,
    EscPosImageMode mode = EscPosImageMode.normal,
  }) {
    EscPosCommandWriter.writeRaster(
      _writer,
      mode: mode.value,
      bytesPerRow: bytesPerRow,
      height: height,
      data: data,
    );
    return this;
  }

  /// Convenience helper to emit a [MonochromeBitmap] raster graphic.
  EscPosPrinter rasterFromMonochrome(
    MonochromeBitmap bitmap, {
    EscPosImageMode mode = EscPosImageMode.normal,
  }) {
    return raster(
      data: bitmap.data,
      bytesPerRow: bitmap.bytesPerRow,
      height: bitmap.height,
      mode: mode,
    );
  }

  /// Emits an auto-cutter cut command (`GS V`).
  ///
  /// If [feedLines] > 0, feeds [feedLines] lines before executing the cut.
  EscPosPrinter cut({
    EscPosCutMode mode = EscPosCutMode.partial,
    int feedLines = 3,
  }) {
    EscPosCommandWriter.writeCut(
      _writer,
      mode: mode.value,
      feedLines: feedLines,
    );
    return this;
  }

  /// Generates a cash drawer kick-out pulse (`ESC p`).
  ///
  /// [onTimeMs] and [offTimeMs] specify pulse timing in milliseconds (0..510 ms).
  /// Both values must be even numbers, and [offTimeMs] must be >= [onTimeMs].
  EscPosPrinter pulseDrawer({
    EscPosDrawerPin pin = EscPosDrawerPin.pin2,
    int onTimeMs = 50,
    int offTimeMs = 100,
  }) {
    EscPosCommandWriter.writePulseDrawer(
      _writer,
      pin: pin.value,
      onTimeMs: onTimeMs,
      offTimeMs: offTimeMs,
    );
    return this;
  }

  /// Emits a real-time status transmission request (`DLE EOT <type>`).
  ///
  /// Note: `DLE EOT` is processed out-of-band in real time by printer hardware.
  /// Applications should coordinate with the transport layer to read the returned status
  /// response before sending subsequent bulk print data.
  EscPosPrinter requestStatus([
    EscPosStatusType type = EscPosStatusType.printer,
  ]) {
    EscPosCommandWriter.writeRealTimeStatus(_writer, type.value);
    return this;
  }

  /// Appends raw binary bytes directly to the command stream without alteration.
  EscPosPrinter rawBytes(Uint8List bytes) {
    EscPosCommandWriter.writeRawBytes(_writer, bytes);
    return this;
  }

  /// Appends a raw ASCII command string directly to the command stream.
  EscPosPrinter rawAscii(String text, {bool appendNewline = false}) {
    EscPosCommandWriter.writeRawAscii(
      _writer,
      text,
      appendNewline: appendNewline,
    );
    return this;
  }

  /// Returns a snapshot of the current binary command stream as [Uint8List].
  ///
  /// This method is idempotent and does NOT reset or mutate the builder.
  Uint8List toBytes() => _writer.toBytes();

  /// Clears all accumulated commands, restores encoding to the constructor configuration,
  /// and resets internal state without emitting bytes.
  void reset() {
    _writer = PrinterByteWriter();
    _applyEncoding(_initialEncoding, emitCommand: false);
  }
}
