import 'dart:typed_data';

import '../byte_writer.dart';
import '../encoding.dart';
import '../languages/tsc_writer.dart';
import '../types.dart';
import 'tsc_types.dart';

/// Protocol-native fluent command-stream builder for TSC / TSPL2 printers.
///
/// Accumulates TSPL commands in deliberate sequential order and emits byte-exact
/// [Uint8List] payloads via [toBytes].
///
/// This builder does NOT manage network, Bluetooth, or USB sockets; generated bytes
/// should be passed to a transport layer.
class TscPrinter {
  final TscEncoding _initialEncoding;
  late TscEncoding _encoding;
  PrinterByteWriter _writer = PrinterByteWriter();

  /// Creates a new [TscPrinter] with the specified default [encoding] (defaults to CP437).
  TscPrinter({TscEncoding encoding = const TscEncoding.cp437()})
      : _initialEncoding = encoding,
        _encoding = encoding {
    if (_encoding.sendCodePageCommand && _encoding.tsplCodePage != null) {
      TscCommandWriter.writeCodePage(_writer, _encoding.tsplCodePage!);
    }
  }

  /// Sets the active text [encoding] for subsequent commands and optionally emits `CODEPAGE`.
  TscPrinter encoding(TscEncoding encoding) {
    _encoding = encoding;
    if (encoding.sendCodePageCommand && encoding.tsplCodePage != null) {
      TscCommandWriter.writeCodePage(_writer, encoding.tsplCodePage!);
    }
    return this;
  }

  /// Emits an explicit `CODEPAGE <codepage>\r\n` command.
  TscPrinter codePage(String codepage) {
    TscCommandWriter.writeCodePage(_writer, codepage);
    return this;
  }

  /// Sets label dimensions in dots (`SIZE <width> dot,<height> dot\r\n`).
  TscPrinter sizeDots(int widthDots, int heightDots) {
    TscCommandWriter.writeSizeDots(_writer, widthDots, heightDots);
    return this;
  }

  /// Sets label dimensions in millimeters (`SIZE <width> mm,<height> mm\r\n`).
  TscPrinter sizeMm({required double widthMm, required double heightMm}) {
    TscCommandWriter.writeSizeMm(_writer, widthMm, heightMm);
    return this;
  }

  /// Sets label dimensions in inches (`SIZE <width>,<height>\r\n`).
  TscPrinter sizeInches({
    required double widthInches,
    required double heightInches,
  }) {
    TscCommandWriter.writeSizeInches(_writer, widthInches, heightInches);
    return this;
  }

  /// Sets label gap distance and offset in dots (`GAP <distance> dot,<offset> dot\r\n`).
  TscPrinter gapDots({required int distanceDots, int offsetDots = 0}) {
    TscCommandWriter.writeGapDots(_writer, distanceDots, offsetDots);
    return this;
  }

  /// Sets label gap distance and offset in millimeters (`GAP <distance> mm,<offset> mm\r\n`).
  TscPrinter gapMm({required double distanceMm, double offsetMm = 0}) {
    TscCommandWriter.writeGapMm(_writer, distanceMm, offsetMm);
    return this;
  }

  /// Sets continuous paper mode with zero gap (`GAP 0 mm,0 mm\r\n`).
  TscPrinter gapContinuous() {
    TscCommandWriter.writeGapContinuous(_writer);
    return this;
  }

  /// Sets black line / mark height and offset in dots (`BLINE <height> dot,<offset> dot\r\n`).
  TscPrinter blineDots({required int heightDots, int offsetDots = 0}) {
    TscCommandWriter.writeBlineDots(_writer, heightDots, offsetDots);
    return this;
  }

  /// Sets black line / mark height and offset in millimeters (`BLINE <height> mm,<offset> mm\r\n`).
  TscPrinter blineMm({required double heightMm, double offsetMm = 0}) {
    TscCommandWriter.writeBlineMm(_writer, heightMm, offsetMm);
    return this;
  }

  /// Sets feed/cut/peel offset in dots (`OFFSET <distance> dot\r\n`).
  TscPrinter offsetDots(int distanceDots) {
    TscCommandWriter.writeOffsetDots(_writer, distanceDots);
    return this;
  }

  /// Sets feed/cut/peel offset in millimeters (`OFFSET <distance> mm\r\n`).
  TscPrinter offsetMm(double distanceMm) {
    TscCommandWriter.writeOffsetMm(_writer, distanceMm);
    return this;
  }

  /// Sets print speed in inches per second (`SPEED <ips>\r\n`).
  TscPrinter speed(double ips) {
    TscCommandWriter.writeSpeed(_writer, ips);
    return this;
  }

  /// Sets print darkness/density (0..15) (`DENSITY <darkness>\r\n`).
  TscPrinter density(int darkness) {
    TscCommandWriter.writeDensity(_writer, darkness);
    return this;
  }

  /// Sets print direction and optional mirroring (`DIRECTION <direction>[,<mirror>]\r\n`).
  TscPrinter direction(TscDirection direction, {bool mirror = false}) {
    TscCommandWriter.writeDirection(
      _writer,
      direction.value,
      mirror ? 1 : null,
    );
    return this;
  }

  /// Sets coordinate reference origin point in dots (`REFERENCE <x>,<y>\r\n`).
  TscPrinter reference(int x, int y) {
    TscCommandWriter.writeReference(_writer, x, y);
    return this;
  }

  /// Shifts the entire print layout in dots (`SHIFT [<x>,]<y>\r\n`).
  TscPrinter shift({int x = 0, int y = 0}) {
    TscCommandWriter.writeShift(_writer, y, x);
    return this;
  }

  /// Clears the printer image buffer (`CLS\r\n`).
  TscPrinter clear() {
    TscCommandWriter.writeCls(_writer);
    return this;
  }

  /// Clears the printer image buffer (`CLS\r\n`). Alias for [clear].
  TscPrinter cls() => clear();

  /// Emits a single-line text element (`TEXT <x>,<y>,"<font>",<rotation>,<xMul>,<yMul>[,<alignment>],"<content>"\r\n`).
  ///
  /// Text is encoded using the active [TscEncoding] (or [customEncoding] if supplied).
  /// Double quotes in [text] are escaped as `\["]`.
  /// Embedded CR/LF newlines are rejected with [InvalidConfigError].
  TscPrinter text({
    required int x,
    required int y,
    required String text,
    TscFont font = TscResidentFont.font2,
    TscRotation rotation = TscRotation.deg0,
    int xMultiplication = 1,
    int yMultiplication = 1,
    TscAlignment? alignment,
    TscEncoding? customEncoding,
  }) {
    final activeEncoding = customEncoding ?? _encoding;
    // Validate that text has no structural newlines and escape quotes
    final escapedText = TscCommandWriter.escapeTscString(text);
    final encoded = activeEncoding.encode(escapedText);

    TscCommandWriter.writeText(
      _writer,
      x: x,
      y: y,
      font: font.name,
      rotation: rotation.degrees,
      xMul: xMultiplication,
      yMul: yMultiplication,
      alignment: alignment?.value,
      encodedContent: encoded,
    );
    return this;
  }

  /// Emits a 1D barcode element (`BARCODE <x>,<y>,"<type>",<height>,<readable>,<rotation>,<narrow>,<wide>[,<alignment>],"<content>"\r\n`).
  TscPrinter barcode({
    required int x,
    required int y,
    required String content,
    required TscBarcodeType type,
    required int height,
    TscBarcodeReadable readable = TscBarcodeReadable.none,
    TscRotation rotation = TscRotation.deg0,
    int narrow = 2,
    int wide = 4,
    TscAlignment? alignment,
  }) {
    TscCommandWriter.writeBarcode(
      _writer,
      x: x,
      y: y,
      type: type.value,
      height: height,
      readable: readable.value,
      rotation: rotation.degrees,
      narrow: narrow,
      wide: wide,
      alignment: alignment?.value,
      content: content,
    );
    return this;
  }

  /// Emits a 2D QR Code element (`QRCODE <x>,<y>,"<ecc>",<cellWidth>,"<mode>",<rotation>[,"<model>"][,"<mask >"],"<content>"\r\n`).
  TscPrinter qrCode({
    required int x,
    required int y,
    required String content,
    TscQrEcc ecc = TscQrEcc.h,
    int cellWidth = 4,
    TscQrMode mode = TscQrMode.auto,
    TscRotation rotation = TscRotation.deg0,
    TscQrModel? model,
    String? mask,
  }) {
    TscCommandWriter.writeQrCode(
      _writer,
      x: x,
      y: y,
      ecc: ecc.value,
      cellWidth: cellWidth,
      mode: mode.value,
      rotation: rotation.degrees,
      model: model?.value,
      mask: mask,
      content: content,
    );
    return this;
  }

  /// Emits a rectangle / box (`BOX <x>,<y>,<xEnd>,<yEnd>,<thickness>[,<radius>]\r\n`).
  TscPrinter box({
    required int x,
    required int y,
    required int xEnd,
    required int yEnd,
    int thickness = 1,
    int? radius,
  }) {
    TscCommandWriter.writeBox(
      _writer,
      x: x,
      y: y,
      xEnd: xEnd,
      yEnd: yEnd,
      thickness: thickness,
      radius: radius,
    );
    return this;
  }

  /// Emits a solid bar / line (`BAR <x>,<y>,<width>,<height>\r\n`).
  TscPrinter bar({
    required int x,
    required int y,
    required int width,
    required int height,
  }) {
    TscCommandWriter.writeBar(
      _writer,
      x: x,
      y: y,
      width: width,
      height: height,
    );
    return this;
  }

  /// Emits a circle outline (`CIRCLE <x>,<y>,<diameter>,<thickness>\r\n`).
  TscPrinter circle({
    required int x,
    required int y,
    required int diameter,
    int thickness = 1,
  }) {
    TscCommandWriter.writeCircle(
      _writer,
      x: x,
      y: y,
      diameter: diameter,
      thickness: thickness,
    );
    return this;
  }

  /// Emits an ellipse outline (`ELLIPSE <x>,<y>,<width>,<height>,<thickness>\r\n`).
  TscPrinter ellipse({
    required int x,
    required int y,
    required int width,
    required int height,
    int thickness = 1,
  }) {
    TscCommandWriter.writeEllipse(
      _writer,
      x: x,
      y: y,
      width: width,
      height: height,
      thickness: thickness,
    );
    return this;
  }

  /// Emits a diagonal line (`DIAGONAL <x1>,<y1>,<x2>,<y2>,<thickness>\r\n`).
  TscPrinter diagonal({
    required int x1,
    required int y1,
    required int x2,
    required int y2,
    int thickness = 1,
  }) {
    TscCommandWriter.writeDiagonal(
      _writer,
      x1: x1,
      y1: y1,
      x2: x2,
      y2: y2,
      thickness: thickness,
    );
    return this;
  }

  /// Inverts colors in a rectangular region (`REVERSE <x>,<y>,<width>,<height>\r\n`).
  TscPrinter reverse({
    required int x,
    required int y,
    required int width,
    required int height,
  }) {
    TscCommandWriter.writeReverse(
      _writer,
      x: x,
      y: y,
      width: width,
      height: height,
    );
    return this;
  }

  /// Clears / erases a rectangular region to white (`ERASE <x>,<y>,<width>,<height>\r\n`).
  TscPrinter erase({
    required int x,
    required int y,
    required int width,
    required int height,
  }) {
    TscCommandWriter.writeErase(
      _writer,
      x: x,
      y: y,
      width: width,
      height: height,
    );
    return this;
  }

  /// Emits a monochrome 1-bit binary bitmap graphic (`BITMAP <x>,<y>,<bytesPerRow>,<height>,<mode>,<binary data>\r\n`).
  ///
  /// [data] must contain exactly [bytesPerRow] * [height] bytes. High-byte values
  /// (0x00..0xFF) are preserved without transformation.
  TscPrinter bitmap({
    required int x,
    required int y,
    required Uint8List data,
    required int bytesPerRow,
    required int height,
    TscBitmapMode mode = TscBitmapMode.overwrite,
  }) {
    TscCommandWriter.writeBitmap(
      _writer,
      x: x,
      y: y,
      bytesPerRow: bytesPerRow,
      height: height,
      mode: mode.value,
      data: data,
    );
    return this;
  }

  /// Convenience helper to emit a [MonochromeBitmap].
  TscPrinter bitmapFromMonochrome(
    MonochromeBitmap bitmap, {
    required int x,
    required int y,
    TscBitmapMode mode = TscBitmapMode.overwrite,
  }) {
    return this.bitmap(
      x: x,
      y: y,
      data: bitmap.data,
      bytesPerRow: bitmap.bytesPerRow,
      height: bitmap.height,
      mode: mode,
    );
  }

  /// Emits label print execution command (`PRINT <sets>[,<copies>]\r\n`).
  TscPrinter print({int sets = 1, int copies = 1}) {
    TscCommandWriter.writePrint(_writer, sets: sets, copies: copies);
    return this;
  }

  /// Feeds the label to the beginning of the next label (`FORMFEED\r\n`).
  TscPrinter formFeed() {
    TscCommandWriter.writeFormFeed(_writer);
    return this;
  }

  /// Calibrates and feeds to the label home position (`HOME\r\n`).
  TscPrinter home() {
    TscCommandWriter.writeHome(_writer);
    return this;
  }

  /// Feeds paper by [dots] (`FEED <dots>\r\n`).
  TscPrinter feed(int dots) {
    TscCommandWriter.writeFeed(_writer, dots);
    return this;
  }

  /// Feeds paper backward by [dots] (`BACKFEED <dots>\r\n`).
  TscPrinter backFeed(int dots) {
    TscCommandWriter.writeBackFeed(_writer, dots);
    return this;
  }

  /// Activates the paper cutter (`CUT\r\n`).
  TscPrinter cut() {
    TscCommandWriter.writeCut(_writer);
    return this;
  }

  /// Activates the printer buzzer/beeper with sound [level] (0..9) and [interval] in milliseconds (1..4095) (`SOUND <level>,<interval>\r\n`).
  TscPrinter sound({required int level, required int interval}) {
    TscCommandWriter.writeSound(_writer, level: level, interval: interval);
    return this;
  }

  /// Emits the immediate status request command `<ESC>!?` (exact bytes: `0x1B, 0x21, 0x3F` without CRLF).
  ///
  /// This command only emits the request bytes into the stream. Receiving and parsing
  /// the returned status response is the responsibility of the transport layer.
  TscPrinter requestStatus() {
    TscCommandWriter.writeImmediateStatus(_writer);
    return this;
  }

  /// Appends raw binary bytes directly to the command stream without alteration.
  TscPrinter rawBytes(Uint8List bytes) {
    TscCommandWriter.writeRawBytes(_writer, bytes);
    return this;
  }

  /// Appends a raw ASCII command string directly to the command stream.
  TscPrinter rawAscii(String command, {bool appendNewline = true}) {
    TscCommandWriter.writeRawAscii(
      _writer,
      command,
      appendNewline: appendNewline,
    );
    return this;
  }

  /// Returns a snapshot of the current binary command stream as [Uint8List].
  ///
  /// This method is idempotent and does NOT reset or mutate the builder.
  Uint8List toBytes() => _writer.toBytes();

  /// Clears all accumulated commands in the builder and restores encoding to constructor defaults.
  void reset() {
    _writer = PrinterByteWriter();
    _encoding = _initialEncoding;
  }
}
