import 'dart:typed_data';

import '../byte_writer.dart';
import '../encoding.dart';
import '../errors.dart';
import '../languages/zpl_writer.dart';
import '../types.dart';
import 'zpl_types.dart';

/// Protocol-native fluent command-stream builder for Zebra ZPL II label printers.
///
/// Accumulates ZPL II commands with explicit format lifecycle boundaries (`startFormat` / `endFormat`)
/// and emits byte-exact [Uint8List] payloads via [toBytes].
///
/// This builder does NOT manage network, USB, or Bluetooth sockets; generated bytes
/// should be passed to a transport layer.
class ZplPrinter {
  final ZplEncoding _initialEncoding;
  late ZplEncoding _activeEncoding;
  bool _inFormat = false;
  PrinterByteWriter _writer = PrinterByteWriter();

  /// Creates a new [ZplPrinter] with the specified default [encoding] (defaults to UTF-8 with ^CI28).
  ZplPrinter({ZplEncoding encoding = const ZplEncoding.utf8()})
      : _initialEncoding = encoding,
        _activeEncoding = encoding;

  /// Whether a format block is currently open (between [startFormat] and [endFormat]).
  bool get inFormat => _inFormat;

  /// Changes the active text encoding and emits `^CI<ciCode>\n` if inside an open format.
  ZplPrinter encoding(ZplEncoding encoding) {
    _activeEncoding = encoding;
    if (_inFormat &&
        encoding.type == ZplTextEncoding.utf8 &&
        encoding.emitCiCommand) {
      ZplCommandWriter.writeCodePage(_writer, 28);
    }
    return this;
  }

  /// Explicitly emits `^CI<ciCode>\n` command.
  ZplPrinter characterInstruction(int ciCode) {
    ZplCommandWriter.writeCodePage(_writer, ciCode);
    return this;
  }

  /// Emits `^XA\n` to start a new label format block.
  ///
  /// If the active encoding specifies `emitCiCommand: true`, also emits `^CI28\n`.
  /// Throws [InvalidConfigError] if a format is already open.
  ZplPrinter startFormat() {
    if (_inFormat) {
      throw InvalidConfigError(
        'Cannot start a new ZPL format while a format is already open (missing endFormat).',
      );
    }
    _inFormat = true;
    ZplCommandWriter.writeStartFormat(_writer);
    if (_activeEncoding.type == ZplTextEncoding.utf8 &&
        _activeEncoding.emitCiCommand) {
      ZplCommandWriter.writeCodePage(_writer, 28);
    }
    return this;
  }

  /// Emits `^XZ\n` to finalize and close the current label format block.
  ///
  /// Throws [InvalidConfigError] if called outside of an open format.
  ZplPrinter endFormat() {
    if (!_inFormat) {
      throw InvalidConfigError(
        'Cannot end ZPL format because no format is currently open (missing startFormat).',
      );
    }
    _inFormat = false;
    ZplCommandWriter.writeEndFormat(_writer);
    return this;
  }

  /// Sets print width in dots (`^PW<dots>\n`).
  ZplPrinter printWidth(int dots) {
    ZplCommandWriter.writePrintWidth(_writer, dots);
    return this;
  }

  /// Sets label length in dots (`^LL<dots>\n`).
  ZplPrinter labelLength(int dots) {
    ZplCommandWriter.writeLabelLength(_writer, dots);
    return this;
  }

  /// Sets print speed in inches per second (`^PR<ips>\n`).
  ZplPrinter speed(int ips) {
    ZplCommandWriter.writeSpeed(_writer, ips);
    return this;
  }

  /// Sets print darkness (`~SD<value>\n`).
  ///
  /// [value] must be between 0.0 and 30.0.
  ZplPrinter darkness(double value) {
    ZplCommandWriter.writeDarkness(_writer, value);
    return this;
  }

  /// Sets print quantity and pause/cut parameters (`^PQ`).
  ZplPrinter printQuantity({
    int copies = 1,
    int pauseAndCut = 0,
    int replicates = 0,
    bool overridePause = false,
  }) {
    ZplCommandWriter.writePrintQuantity(
      _writer,
      copies: copies,
      pauseAndCut: pauseAndCut,
      replicates: replicates,
      overridePause: overridePause,
    );
    return this;
  }

  /// Positions the next field at top-left origin coordinates [x], [y] (`^FO<x>,<y>`).
  ZplPrinter fieldOrigin(int x, int y) {
    ZplCommandWriter.writeFieldOrigin(_writer, x, y);
    return this;
  }

  /// Positions the next field at baseline typeset coordinates [x], [y] (`^FT<x>,<y>`).
  ZplPrinter fieldTypeset(int x, int y) {
    ZplCommandWriter.writeFieldTypeset(_writer, x, y);
    return this;
  }

  /// Selects font and orientation for the active field (`^A<font><rot>,<h>,<w>`).
  ZplPrinter font({
    ZplFont font = ZplFont.font0,
    ZplRotation rotation = ZplRotation.unrotated,
    int height = 30,
    int? width,
  }) {
    ZplCommandWriter.writeFont(
      _writer,
      fontCode: font.code,
      rotationCode: rotation.code,
      height: height,
      width: width,
    );
    return this;
  }

  /// Formats the active field as a text block (`^FB<width>,<maxLines>,<lineSpacing>,<align>,<hangingIndent>`).
  ZplPrinter fieldBlock({
    required int width,
    int maxLines = 1,
    int lineSpacing = 0,
    String align = 'L',
    int hangingIndent = 0,
  }) {
    ZplCommandWriter.writeFieldBlock(
      _writer,
      width: width,
      maxLines: maxLines,
      lineSpacing: lineSpacing,
      align: align,
      hangingIndent: hangingIndent,
    );
    return this;
  }

  /// Enables reverse white-on-black print for the active field (`^FR`).
  ZplPrinter fieldReverse() {
    ZplCommandWriter.writeFieldReverse(_writer);
    return this;
  }

  /// Appends field data content (`^FD<text>` or `^FH^FD<escaped>`).
  ZplPrinter fieldData(String text, {bool useHexEscape = false}) {
    ZplCommandWriter.writeFieldData(
      _writer,
      text: text,
      isUtf8: _activeEncoding.type == ZplTextEncoding.utf8,
      useHexEscape: useHexEscape,
    );
    return this;
  }

  /// Concludes and prints the active field (`^FS\n`).
  ZplPrinter fieldSeparator() {
    ZplCommandWriter.writeFieldSeparator(_writer);
    return this;
  }

  /// Emits a complete text field sequence with positioning, font, and automatic `^FH` escaping.
  ZplPrinter text({
    required int x,
    required int y,
    required String text,
    ZplFont font = ZplFont.font0,
    ZplRotation rotation = ZplRotation.unrotated,
    int height = 30,
    int? width,
    int? maxWidth,
    String? align,
    bool reverse = false,
    ZplPositionMode positionMode = ZplPositionMode.origin,
  }) {
    if (positionMode == ZplPositionMode.typeset) {
      fieldTypeset(x, y);
    } else {
      fieldOrigin(x, y);
    }

    this.font(font: font, rotation: rotation, height: height, width: width);

    if (maxWidth != null) {
      final a = align == 'center' || align == 'C'
          ? 'C'
          : align == 'right' || align == 'R'
              ? 'R'
              : align == 'justified' || align == 'J'
                  ? 'J'
                  : 'L';
      fieldBlock(width: maxWidth, align: a);
    }

    if (reverse) {
      fieldReverse();
    }

    fieldData(text);
    fieldSeparator();
    return this;
  }

  /// Emits a 1D barcode sequence (`^BC`, `^B3`, etc.).
  ZplPrinter barcode({
    required int x,
    required int y,
    required String content,
    ZplBarcodeType type = ZplBarcodeType.code128,
    int height = 50,
    bool interpretationLine = false,
    bool interpretationAbove = false,
    ZplRotation rotation = ZplRotation.unrotated,
    ZplPositionMode positionMode = ZplPositionMode.origin,
  }) {
    ZplCommandWriter.writeBarcode(
      _writer,
      x: x,
      y: y,
      typeCode: type.code,
      rotCode: rotation.code,
      height: height,
      interpretationLine: interpretationLine,
      interpretationAbove: interpretationAbove,
      content: content,
      useTypeset: positionMode == ZplPositionMode.typeset,
    );
    return this;
  }

  /// Emits a 2D QR Code (`^BQ`).
  ///
  /// [magnification] specifies module size (1..100 dots).
  /// [mask] specifies initial mask value (0..7, defaults to 7).
  ZplPrinter qrCode({
    required int x,
    required int y,
    required String content,
    int magnification = 4,
    ZplQrEcc ecc = ZplQrEcc.q,
    ZplQrModel model = ZplQrModel.model2,
    int mask = 7,
    ZplPositionMode positionMode = ZplPositionMode.origin,
  }) {
    ZplCommandWriter.writeQrCode(
      _writer,
      x: x,
      y: y,
      model: model.value,
      magnification: magnification,
      eccCode: ecc.code,
      mask: mask,
      content: content,
      isUtf8: _activeEncoding.type == ZplTextEncoding.utf8,
      useTypeset: positionMode == ZplPositionMode.typeset,
    );
    return this;
  }

  /// Emits a 1-bit raster bit image in ASCII hex format (`^GFA`).
  ZplPrinter graphicField({
    required int x,
    required int y,
    required Uint8List data,
    required int bytesPerRow,
    required int height,
    ZplPositionMode positionMode = ZplPositionMode.origin,
  }) {
    ZplCommandWriter.writeGraphicField(
      _writer,
      x: x,
      y: y,
      bytesPerRow: bytesPerRow,
      height: height,
      data: data,
      useTypeset: positionMode == ZplPositionMode.typeset,
    );
    return this;
  }

  /// Convenience helper to emit a [MonochromeBitmap] graphic field.
  ZplPrinter graphicFieldFromMonochrome(
    MonochromeBitmap bitmap, {
    required int x,
    required int y,
    ZplPositionMode positionMode = ZplPositionMode.origin,
  }) {
    return graphicField(
      x: x,
      y: y,
      data: bitmap.data,
      bytesPerRow: bitmap.bytesPerRow,
      height: bitmap.height,
      positionMode: positionMode,
    );
  }

  /// Emits a Graphic Box (`^GB`).
  ZplPrinter box({
    required int x,
    required int y,
    required int width,
    required int height,
    int thickness = 1,
    int radius = 0,
    bool white = false,
  }) {
    ZplCommandWriter.writeBox(
      _writer,
      x: x,
      y: y,
      width: width,
      height: height,
      thickness: thickness,
      radius: radius,
      white: white,
    );
    return this;
  }

  /// Emits a line segment (`^GB` for orthogonal lines, `^GD` for diagonal lines).
  ZplPrinter line({
    required int x1,
    required int y1,
    required int x2,
    required int y2,
    int thickness = 1,
  }) {
    if (y1 == y2) {
      final x = x1 < x2 ? x1 : x2;
      final w = (x2 - x1).abs();
      box(
        x: x,
        y: y1,
        width: w == 0 ? 1 : w,
        height: thickness,
        thickness: thickness,
      );
    } else if (x1 == x2) {
      final y = y1 < y2 ? y1 : y2;
      final h = (y2 - y1).abs();
      box(
        x: x1,
        y: y,
        width: thickness,
        height: h == 0 ? 1 : h,
        thickness: thickness,
      );
    } else {
      final w = (x2 - x1).abs();
      final h = (y2 - y1).abs();
      final x = x1 < x2 ? x1 : x2;
      final y = y1 < y2 ? y1 : y2;
      final dir = ((x2 > x1) == (y2 > y1)) ? 'R' : 'L';
      ZplCommandWriter.writeDiagonal(
        _writer,
        x: x,
        y: y,
        width: w == 0 ? 1 : w,
        height: h == 0 ? 1 : h,
        thickness: thickness,
        direction: dir,
      );
    }
    return this;
  }

  /// Emits a Graphic Circle (`^GC`).
  ZplPrinter circle({
    required int x,
    required int y,
    required int diameter,
    int thickness = 1,
  }) {
    ZplCommandWriter.writeCircle(
      _writer,
      x: x,
      y: y,
      diameter: diameter,
      thickness: thickness,
    );
    return this;
  }

  /// Emits an erase rectangle (`^GB` with white fill).
  ZplPrinter erase({
    required int x,
    required int y,
    required int width,
    required int height,
  }) {
    box(
      x: x,
      y: y,
      width: width,
      height: height,
      thickness: width,
      white: true,
    );
    return this;
  }

  /// Appends raw binary bytes directly to the command stream.
  ZplPrinter rawBytes(Uint8List bytes) {
    ZplCommandWriter.writeRawBytes(_writer, bytes);
    return this;
  }

  /// Appends a raw ASCII command string directly to the command stream.
  ZplPrinter rawAscii(String text, {bool appendNewline = false}) {
    ZplCommandWriter.writeRawAscii(_writer, text, appendNewline: appendNewline);
    return this;
  }

  /// Returns a snapshot of the current binary command stream as [Uint8List].
  ///
  /// This method is idempotent and does NOT mutate, reset, or auto-append `^XZ`.
  Uint8List toBytes() => _writer.toBytes();

  /// Clears all accumulated commands, restores encoding to the constructor configuration,
  /// resets format state, and emits zero bytes.
  void reset() {
    _writer = PrinterByteWriter();
    _inFormat = false;
    _activeEncoding = _initialEncoding;
  }
}
