name: portakal_workspace
description: "Monorepo workspace for Portakal universal printer SDK."
publish_to: "none"

environment:
  sdk: "^3.6.0"

workspace:
  - packages/portakal_core
  - packages/portakal_flutter
  - example
