import 'dart:typed_data';

import '../byte_writer.dart';
import '../encoding.dart';
import '../errors.dart';
import '../languages/dpl_writer.dart';
import 'dpl_types.dart';

/// Protocol-native fluent command-stream builder for Datamax DPL label printers.
///
/// Accumulates DPL commands in deliberate sequential order and emits byte-exact
/// [Uint8List] payloads via [toBytes].
///
/// This builder does NOT manage network, Bluetooth, or USB sockets; generated bytes
/// should be passed to a transport layer.
class DplPrinter {
  final DplEncoding _initialEncoding;
  late DplEncoding _activeEncoding;
  late CodePageEncoder _encoder;
  bool _inLabel = false;
  PrinterByteWriter _writer = PrinterByteWriter();

  /// Creates a new [DplPrinter] with the specified default [encoding] (defaults to legacy CP437).
  DplPrinter({DplEncoding encoding = const DplEncoding.legacy()})
    : _initialEncoding = encoding {
    _applyEncoding(encoding);
  }

  void _applyEncoding(DplEncoding enc) {
    _activeEncoding = enc;
    _encoder = getEncoder(enc.codePage);
  }

  /// Whether a label formatting block is currently open (between [startLabel] and [endLabel]).
  bool get inLabel => _inLabel;

  /// Sets the active text [encoding] for subsequent commands.
  DplPrinter encoding(DplEncoding encoding) {
    _applyEncoding(encoding);
    return this;
  }

  /// Emits `<STX>L\n` (0x02, 'L', 0x0A) to begin label formatting mode.
  ///
  /// Throws [InvalidConfigError] if a label block is already open.
  DplPrinter startLabel() {
    if (_inLabel) {
      throw InvalidConfigError(
        'Cannot start DPL label while a label formatting block is already open.',
      );
    }
    _inLabel = true;
    DplCommandWriter.writeStartLabel(_writer);
    return this;
  }

  /// Emits `E\n` (0x45, 0x0A) to end label formatting mode and trigger printing.
  ///
  /// Throws [InvalidConfigError] if called outside of an open label block.
  DplPrinter endLabel() {
    if (!_inLabel) {
      throw InvalidConfigError(
        'Cannot end DPL label because no label formatting block is currently open.',
      );
    }
    _inLabel = false;
    DplCommandWriter.writeEndLabel(_writer);
    return this;
  }

  /// Alias for [endLabel] to finalize and print the label.
  DplPrinter print() => endLabel();

  /// Sets print heat / darkness (00..30) (`D<heat:2>\n`).
  DplPrinter heat(int heat) {
    DplCommandWriter.writeHeat(_writer, heat);
    return this;
  }

  /// Alias for [heat] (`D<heat:2>\n`).
  DplPrinter density(int density) => heat(density);

  /// Sets print speed (01..14) (`S<speed:2>\n`).
  DplPrinter speed(int speed) {
    DplCommandWriter.writeSpeed(_writer, speed);
    return this;
  }

  /// Sets label width in dots (0001..9999) (`A<width:4>\n`).
  DplPrinter labelWidth(int widthDots) {
    DplCommandWriter.writeWidth(_writer, widthDots);
    return this;
  }

  /// Sets print copies quantity (0001..9999) (`Q<copies:4>\n`).
  DplPrinter copies(int quantity) {
    DplCommandWriter.writeCopies(_writer, quantity);
    return this;
  }

  /// Emits a text record: `<rot><y:4><x:4><font><xMul:2><yMul:2><content>\n`.
  DplPrinter text({
    required int x,
    required int y,
    required String text,
    String font = '0',
    int xMultiplier = 1,
    int yMultiplier = 1,
    DplRotation rotation = DplRotation.unrotated,
  }) {
    DplCommandWriter.writeText(
      _writer,
      x: x,
      y: y,
      font: font,
      xMultiplier: xMultiplier,
      yMultiplier: yMultiplier,
      rotationCode: rotation.code,
      text: text,
      encoder: _encoder,
      replaceUnsupported: _activeEncoding.replaceUnsupported,
    );
    return this;
  }

  /// Emits a 1D barcode: `<rot><type><wide:1>0<height:3>0000<x:4><y:4><content>\n`.
  DplPrinter barcode({
    required int x,
    required int y,
    required String content,
    DplBarcodeType type = DplBarcodeType.code128,
    int height = 40,
    int wideMultiplier = 2,
    DplRotation rotation = DplRotation.unrotated,
  }) {
    DplCommandWriter.writeBarcode(
      _writer,
      x: x,
      y: y,
      typeCode: type.code,
      wideMultiplier: wideMultiplier,
      height: height,
      rotationCode: rotation.code,
      content: content,
    );
    return this;
  }

  /// Emits a 2D QR Code: `1W1c<cellWidth:3>0000<x:4><y:4><content>\n`.
  DplPrinter qrCode({
    required int x,
    required int y,
    required String content,
    int cellWidth = 4,
  }) {
    DplCommandWriter.writeQrCode(
      _writer,
      x: x,
      y: y,
      cellWidth: cellWidth,
      content: content,
    );
    return this;
  }

  /// Emits a box rectangle: `1e<y:4><x:4><width:4><height:4><thickness:4>\n`.
  DplPrinter box({
    required int x,
    required int y,
    required int width,
    required int height,
    int thickness = 1,
  }) {
    DplCommandWriter.writeBox(
      _writer,
      x: x,
      y: y,
      width: width,
      height: height,
      thickness: thickness,
    );
    return this;
  }

  /// Emits a line segment: `1X<y:4><x:4>L<length:4><thickness>\n`.
  DplPrinter line({
    required int x1,
    required int y1,
    required int x2,
    required int y2,
    int thickness = 1,
  }) {
    DplCommandWriter.writeLine(
      _writer,
      x1: x1,
      y1: y1,
      x2: x2,
      y2: y2,
      thickness: thickness,
    );
    return this;
  }

  /// Appends raw binary bytes directly to the command stream without alteration.
  DplPrinter rawBytes(Uint8List bytes) {
    DplCommandWriter.writeRawBytes(_writer, bytes);
    return this;
  }

  /// Appends a raw ASCII command string directly to the command stream.
  DplPrinter rawAscii(String command, {bool appendNewline = false}) {
    DplCommandWriter.writeRawAscii(
      _writer,
      command,
      appendNewline: appendNewline,
    );
    return this;
  }

  /// Returns a snapshot of the current binary command stream as [Uint8List].
  ///
  /// This method is idempotent and does NOT reset, mutate, or auto-append `E\n`.
  Uint8List toBytes() => _writer.toBytes();

  /// Clears all accumulated commands, resets format state, and restores encoding to constructor defaults.
  void reset() {
    _writer = PrinterByteWriter();
    _inLabel = false;
    _applyEncoding(_initialEncoding);
  }
}
