import 'dart:typed_data';

import '../byte_writer.dart';
import '../encoding.dart';
import '../languages/ipl_writer.dart';
import 'ipl_types.dart';

/// Protocol-native fluent command-stream builder for Intermec IPL printers.
///
/// Accumulates IPL commands in deliberate sequential order and emits byte-exact
/// [Uint8List] payloads via [toBytes] using real binary control bytes:
/// - STX (0x02)
/// - ETX (0x03)
/// - ESC (0x1B)
/// - SI  (0x0F)
///
/// This builder does NOT manage network, Bluetooth, or USB sockets; generated bytes
/// should be passed to a transport layer.
class IplPrinter {
  final IplEncoding _initialEncoding;
  late IplEncoding _activeEncoding;
  late CodePageEncoder _encoder;
  int _fieldCounter = 0;
  PrinterByteWriter _writer = PrinterByteWriter();

  /// Creates a new [IplPrinter] with the specified default [encoding] (defaults to legacy CP437).
  IplPrinter({IplEncoding encoding = const IplEncoding.legacy()})
    : _initialEncoding = encoding {
    _applyEncoding(encoding);
  }

  void _applyEncoding(IplEncoding enc) {
    _activeEncoding = enc;
    _encoder = getEncoder(enc.codePage);
  }

  /// Sets the active text [encoding] for subsequent commands.
  IplPrinter encoding(IplEncoding encoding) {
    _applyEncoding(encoding);
    return this;
  }

  /// Emits `<STX><ESC>C<formatNumber><ETX>` — Create Format (Advanced Mode).
  IplPrinter createFormat([int formatNumber = 1]) {
    IplCommandWriter.writeCreateFormat(_writer, formatNumber);
    return this;
  }

  /// Emits `<STX><ESC>P<ETX>` — Enter Program Mode.
  IplPrinter programMode() {
    IplCommandWriter.writeProgramMode(_writer);
    return this;
  }

  /// Emits `<STX><SI>L<heightDots><ETX>` — Set Label Length / Height.
  IplPrinter labelLength(int heightDots) {
    IplCommandWriter.writeLabelLength(_writer, heightDots);
    return this;
  }

  /// Emits `<STX><SI>W<widthDots><ETX>` — Set Label Width.
  IplPrinter labelWidth(int widthDots) {
    IplCommandWriter.writeLabelWidth(_writer, widthDots);
    return this;
  }

  /// Emits `<STX><SI>S<speed>0<ETX>` — Set Print Speed.
  IplPrinter speed(int speed) {
    IplCommandWriter.writeSpeed(_writer, speed);
    return this;
  }

  /// Emits `<STX><SI>d<density><ETX>` — Set Print Density / Darkness.
  IplPrinter density(int density) {
    IplCommandWriter.writeDensity(_writer, density);
    return this;
  }

  /// Emits `<STX><ESC>M<copies><ETX>` — Set Print Quantity / Copies.
  IplPrinter copies(int quantity) {
    IplCommandWriter.writeCopies(_writer, quantity);
    return this;
  }

  /// Emits a text field: `<STX>H<fieldNum>;o<x>,<y>;f<rot>;h<fh>;w<fw>;c<font>;d3,<text><ETX>`.
  IplPrinter text({
    required int x,
    required int y,
    required String text,
    int fieldNumber = 0,
    int fontHeight = 12,
    int fontWidth = 12,
    int fontCode = 26,
    IplRotation rotation = IplRotation.unrotated,
  }) {
    final num = fieldNumber > 0 ? fieldNumber : ++_fieldCounter;
    IplCommandWriter.writeTextField(
      _writer,
      fieldNumber: num,
      x: x,
      y: y,
      rotation: rotation.code,
      fontHeight: fontHeight,
      fontWidth: fontWidth,
      fontCode: fontCode,
      text: text,
      encoder: _encoder,
      replaceUnsupported: _activeEncoding.replaceUnsupported,
    );
    return this;
  }

  /// Emits a box rectangle: `<STX>W<fieldNum>;o<x>,<y>;f0;l<width>;h<height>;w<thickness><ETX>`.
  IplPrinter box({
    required int x,
    required int y,
    required int width,
    required int height,
    int fieldNumber = 0,
    int thickness = 1,
  }) {
    final num = fieldNumber > 0 ? fieldNumber : ++_fieldCounter;
    IplCommandWriter.writeBoxField(
      _writer,
      fieldNumber: num,
      x: x,
      y: y,
      width: width,
      height: height,
      thickness: thickness,
    );
    return this;
  }

  /// Emits a line segment: `<STX>L<fieldNum>;o<x>,<y>;f<rot>;l<length>;w<thickness><ETX>`.
  IplPrinter line({
    required int x1,
    required int y1,
    required int x2,
    required int y2,
    int fieldNumber = 0,
    int thickness = 1,
  }) {
    final num = fieldNumber > 0 ? fieldNumber : ++_fieldCounter;
    if (y1 == y2) {
      // Horizontal line
      final x = x1 < x2 ? x1 : x2;
      final len = (x2 - x1).abs();
      IplCommandWriter.writeLineField(
        _writer,
        fieldNumber: num,
        x: x,
        y: y1,
        length: len == 0 ? 1 : len,
        thickness: thickness,
        isVertical: false,
      );
    } else {
      // Vertical line
      final y = y1 < y2 ? y1 : y2;
      final len = (y2 - y1).abs();
      IplCommandWriter.writeLineField(
        _writer,
        fieldNumber: num,
        x: x1,
        y: y,
        length: len == 0 ? 1 : len,
        thickness: thickness,
        isVertical: true,
      );
    }
    return this;
  }

  /// Emits a 1D barcode field definition + data frame.
  IplPrinter barcode({
    required int y,
    required String content,
    int fieldNumber = 1,
    int height = 40,
    int wideMultiplier = 2,
    IplBarcodeType type = IplBarcodeType.code128,
  }) {
    IplCommandWriter.writeBarcodeField(
      _writer,
      fieldNumber: fieldNumber,
      y: y,
      height: height,
      wideMultiplier: wideMultiplier,
      content: content,
      symbologyCode: type.code,
    );
    return this;
  }

  /// Emits a 2D QR Code field definition + data frame.
  IplPrinter qrCode({
    required int y,
    required String content,
    int fieldNumber = 2,
    int cellWidth = 4,
  }) {
    IplCommandWriter.writeQrCodeField(
      _writer,
      fieldNumber: fieldNumber,
      y: y,
      cellWidth: cellWidth,
      content: content,
    );
    return this;
  }

  /// Emits `<STX><ESC>E<formatNumber><ETX>` — End Format.
  IplPrinter endFormat([int formatNumber = 1]) {
    IplCommandWriter.writeEndFormat(_writer, formatNumber);
    return this;
  }

  /// Emits `<STX>R<ETX>` — Print / Execute Format.
  IplPrinter print() {
    IplCommandWriter.writePrint(_writer);
    return this;
  }

  /// Appends raw binary bytes directly to the command stream without alteration.
  IplPrinter rawBytes(Uint8List bytes) {
    IplCommandWriter.writeRawBytes(_writer, bytes);
    return this;
  }

  /// Appends a raw ASCII command string directly to the command stream.
  IplPrinter rawAscii(String command) {
    IplCommandWriter.writeRawAscii(_writer, command);
    return this;
  }

  /// Returns a snapshot of the current binary command stream as [Uint8List].
  ///
  /// This method is idempotent and does NOT reset, mutate, or auto-finalize the job.
  Uint8List toBytes() => _writer.toBytes();

  /// Clears all accumulated commands, resets field counters, and restores encoding to constructor defaults.
  void reset() {
    _writer = PrinterByteWriter();
    _fieldCounter = 0;
    _applyEncoding(_initialEncoding);
  }
}
