import 'dart:typed_data';

import '../byte_writer.dart';
import '../encoding.dart';
import '../languages/sbpl_writer.dart';
import 'sbpl_types.dart';

/// Protocol-native fluent command-stream builder for SATO SBPL printers.
///
/// Accumulates SBPL commands in deliberate sequential order and emits byte-exact
/// [Uint8List] payloads via [toBytes] using real binary ESC (0x1B) control sequences:
/// - `ESC A`: Start Job
/// - `ESC CS<speed>`: Print Speed
/// - `ESC H<xxxx>` / `ESC V<yyyy>`: Coordinate Positioning
/// - `ESC L<hh><ww>`: Text Magnification
/// - `ESC %<rot>`: Text Rotation
/// - `ESC K9B`: Font / Text Output
/// - `ESC FW...`: Box & Line Primitives
/// - `ESC B1` / `ESC BG`: Code 39 & Code 128 Barcodes
/// - `ESC BQ`: QR Code
/// - `ESC Q<n>`: Print Copies
/// - `ESC Z`: End Job
///
/// Generic raster graphics are currently unsupported in the native baseline due to
/// cross-model dialect variability of `ESC G`.
///
/// This builder does NOT manage network, Bluetooth, or USB sockets; generated bytes
/// should be passed to a transport layer.
class SbplPrinter {
  final SbplEncoding _initialEncoding;
  late SbplEncoding _activeEncoding;
  late CodePageEncoder _encoder;
  PrinterByteWriter _writer = PrinterByteWriter();

  /// Creates a new [SbplPrinter] with the specified default [encoding] (defaults to legacy CP437).
  SbplPrinter({SbplEncoding encoding = const SbplEncoding.legacy()})
    : _initialEncoding = encoding {
    _applyEncoding(encoding);
  }

  void _applyEncoding(SbplEncoding enc) {
    _activeEncoding = enc;
    _encoder = getEncoder(enc.codePage);
  }

  /// Sets the active text [encoding] for subsequent commands.
  SbplPrinter encoding(SbplEncoding encoding) {
    _applyEncoding(encoding);
    return this;
  }

  /// Emits `ESC A` — Start Job.
  SbplPrinter startJob() {
    SbplCommandWriter.writeStartJob(_writer);
    return this;
  }

  /// Emits `ESC CS<speed>` — Set Print Speed.
  SbplPrinter speed(int speed) {
    SbplCommandWriter.writePrintSpeed(_writer, speed);
    return this;
  }

  /// Emits a text field with positioning, rotation, magnification, font, and encoded payload.
  SbplPrinter text({
    required int x,
    required int y,
    required String text,
    int widthMag = 1,
    int heightMag = 1,
    SbplFont font = SbplFont.k9b,
    SbplRotation rotation = SbplRotation.unrotated,
  }) {
    SbplCommandWriter.writeText(
      _writer,
      x: x,
      y: y,
      text: text,
      encoder: _encoder,
      replaceUnsupported: _activeEncoding.replaceUnsupported,
      widthMag: widthMag,
      heightMag: heightMag,
      fontCode: font.code,
      rotation: rotation.code,
    );
    return this;
  }

  /// Emits a box rectangle: `ESC H<x> ESC V<y> ESC FW<t>V<h>H<w>`.
  SbplPrinter box({
    required int x,
    required int y,
    required int width,
    required int height,
    int thickness = 1,
  }) {
    SbplCommandWriter.writeBox(
      _writer,
      x: x,
      y: y,
      width: width,
      height: height,
      thickness: thickness,
    );
    return this;
  }

  /// Emits a line segment: `ESC H<x> ESC V<y> ESC FW<t>H<w>` or `FW<t>V<h>`.
  SbplPrinter line({
    required int x1,
    required int y1,
    required int x2,
    required int y2,
    int thickness = 1,
  }) {
    SbplCommandWriter.writeLine(
      _writer,
      x1: x1,
      y1: y1,
      x2: x2,
      y2: y2,
      thickness: thickness,
    );
    return this;
  }

  /// Emits a 1D barcode: `ESC V<y> ESC H<x> ESC <type><narrow>0<height><content>`.
  SbplPrinter barcode({
    required int x,
    required int y,
    required String content,
    int height = 40,
    int narrow = 2,
    SbplBarcodeType type = SbplBarcodeType.code128,
  }) {
    SbplCommandWriter.writeBarcode(
      _writer,
      x: x,
      y: y,
      content: content,
      typeCode: type.code,
      narrow: narrow,
      height: height,
    );
    return this;
  }

  /// Emits a 2D QR Code: `ESC V<y> ESC H<x> ESC BQ<cellWidth>200<content>`.
  SbplPrinter qrCode({
    required int x,
    required int y,
    required String content,
    int cellWidth = 4,
  }) {
    SbplCommandWriter.writeQrCode(
      _writer,
      x: x,
      y: y,
      content: content,
      cellWidth: cellWidth,
    );
    return this;
  }

  /// Emits `ESC Q<copies>` — Print Copies.
  SbplPrinter copies(int count) {
    SbplCommandWriter.writeCopies(_writer, count);
    return this;
  }

  /// Emits `ESC Z` — End Job.
  SbplPrinter endJob() {
    SbplCommandWriter.writeEndJob(_writer);
    return this;
  }

  /// Appends raw binary bytes directly to the command stream without alteration.
  SbplPrinter rawBytes(Uint8List bytes) {
    SbplCommandWriter.writeRawBytes(_writer, bytes);
    return this;
  }

  /// Appends a raw ASCII command string directly to the command stream.
  SbplPrinter rawAscii(String command, {bool appendNewline = false}) {
    SbplCommandWriter.writeRawAscii(
      _writer,
      command,
      appendNewline: appendNewline,
    );
    return this;
  }

  /// Returns a snapshot of the current binary command stream as [Uint8List].
  ///
  /// This method is idempotent and does NOT reset, mutate, or auto-finalize the job.
  Uint8List toBytes() => _writer.toBytes();

  /// Clears all accumulated commands and restores encoding to constructor defaults.
  void reset() {
    _writer = PrinterByteWriter();
    _applyEncoding(_initialEncoding);
  }
}
