import 'dart:typed_data';

import '../byte_writer.dart';
import '../encoding.dart';
import '../languages/starprnt_writer.dart';
import '../types.dart';
import 'starprnt_types.dart';

/// Protocol-native fluent command-stream builder for Star Line Mode / StarPRNT receipt printers.
///
/// Accumulates commands in deliberate sequential order and emits byte-exact
/// [Uint8List] payloads via [toBytes] using authentic Star Line Mode binary commands:
/// - `ESC @`: Initialize printer
/// - `ESC GS t <n>`: Character code page selection
/// - `ESC GS a <n>`: Alignment (Left, Center, Right)
/// - `ESC E` / `ESC F`: Bold ON / OFF
/// - `ESC - <n>`: Underline ON / OFF
/// - `ESC 4` / `ESC 5`: Invert ON / OFF
/// - `ESC i <h> <w>`: Character expansion sizing
/// - `ESC a <n>` / `ESC J <n>`: Feed lines / dots
/// - `ESC d <n>`: Full and partial auto-cutting
/// - `BEL`: Cash drawer kick
/// - `ESC b <type> <readable> <wide> <height> <content> RS`: 1D Barcodes
/// - `ESC GS y ...`: 2D QR Code command family
/// - `ESC * r A` ... `b nL nH <data>` ... `ESC * r B`: Binary raster mode
///
/// This builder does NOT manage network, Bluetooth, or USB sockets; generated bytes
/// should be passed to a transport layer.
class StarPrntPrinter {
  final StarPrntEncoding _initialEncoding;
  late StarPrntEncoding _activeEncoding;
  late CodePageEncoder _encoder;
  PrinterByteWriter _writer = PrinterByteWriter();

  /// Creates a new [StarPrntPrinter] with the specified default [encoding] (defaults to legacy CP437).
  StarPrntPrinter({StarPrntEncoding encoding = const StarPrntEncoding.legacy()})
    : _initialEncoding = encoding {
    _applyEncoding(encoding, emitCommand: true);
  }

  void _applyEncoding(StarPrntEncoding enc, {bool emitCommand = false}) {
    _activeEncoding = enc;
    _encoder = getEncoder(enc.codePage);
    if (emitCommand && enc.sendCodePageCommand && enc.characterTable != null) {
      StarPrntCommandWriter.writeCodePage(_writer, enc.characterTable!);
    }
  }

  /// Sets the active text [encoding] for subsequent commands, emitting `ESC GS t <n>` if configured.
  StarPrntPrinter encoding(StarPrntEncoding encoding) {
    _applyEncoding(encoding, emitCommand: true);
    return this;
  }

  /// Emits `ESC @` — Initialize Printer.
  StarPrntPrinter initialize() {
    StarPrntCommandWriter.writeInitialize(_writer);
    return this;
  }

  /// Appends text content encoded with the active code page encoder.
  StarPrntPrinter text(String text) {
    StarPrntCommandWriter.writeText(
      _writer,
      text,
      _encoder,
      replaceUnsupported: _activeEncoding.replaceUnsupported,
    );
    return this;
  }

  /// Appends text content followed by a line feed (0x0A).
  StarPrntPrinter textLine([String text = '']) {
    if (text.isNotEmpty) {
      this.text(text);
    }
    return lineFeed();
  }

  /// Emits a single line feed byte (0x0A).
  StarPrntPrinter lineFeed() {
    StarPrntCommandWriter.writeLineFeed(_writer);
    return this;
  }

  /// Emits `ESC a <lines>` — Feed Paper by Lines.
  StarPrntPrinter feedLines(int lines) {
    StarPrntCommandWriter.writeFeedLines(_writer, lines);
    return this;
  }

  /// Emits `ESC J <dots>` — Feed Paper by Dots.
  StarPrntPrinter feedDots(int dots) {
    StarPrntCommandWriter.writeFeedDots(_writer, dots);
    return this;
  }

  /// Emits `ESC GS a <n>` — Select Alignment (Left, Center, Right).
  StarPrntPrinter align(StarAlignment alignment) {
    StarPrntCommandWriter.writeAlignment(_writer, alignment.code);
    return this;
  }

  /// Emits `ESC E` (Bold ON) or `ESC F` (Bold OFF).
  StarPrntPrinter bold([bool enable = true]) {
    StarPrntCommandWriter.writeBold(_writer, enable);
    return this;
  }

  /// Emits `ESC - <mode>` — Underline ON (1-dot) or OFF.
  StarPrntPrinter underline([bool enable = true]) {
    StarPrntCommandWriter.writeUnderline(_writer, enable ? 1 : 0);
    return this;
  }

  /// Emits `ESC 4` (Invert ON) or `ESC 5` (Invert OFF).
  StarPrntPrinter invert([bool enable = true]) {
    StarPrntCommandWriter.writeInvert(_writer, enable);
    return this;
  }

  /// Emits `ESC i <h> <w>` — Character Expansion Multipliers (1..6).
  StarPrntPrinter size({int widthMultiplier = 1, int heightMultiplier = 1}) {
    StarPrntCommandWriter.writeCharacterSize(
      _writer,
      widthMultiplier: widthMultiplier,
      heightMultiplier: heightMultiplier,
    );
    return this;
  }

  /// Emits `ESC d <mode>` — Cut Paper (defaults to partial cut).
  StarPrntPrinter cut([StarCutMode mode = StarCutMode.partial]) {
    StarPrntCommandWriter.writeCut(_writer, mode.code);
    return this;
  }

  /// Emits `BEL` (0x07) — Kick Cash Drawer Channel 1.
  StarPrntPrinter pulseDrawer([int channel = 1]) {
    StarPrntCommandWriter.writePulseDrawer(_writer, channel);
    return this;
  }

  /// Emits `ESC b <type> <readable> <wide> <height> <content> RS` — 1D Barcode.
  StarPrntPrinter barcode(
    String content, {
    StarBarcodeType type = StarBarcodeType.code128,
    int height = 40,
    int wide = 2,
    bool readable = false,
  }) {
    StarPrntCommandWriter.writeBarcode(
      _writer,
      typeCode: type.code,
      content: content,
      readable: readable ? 2 : 1,
      wide: wide,
      height: height,
    );
    return this;
  }

  /// Emits the Star Line Mode QR code command sequence.
  StarPrntPrinter qrCode(
    String content, {
    int cellWidth = 4,
    StarQrEcc ecc = StarQrEcc.m,
    StarQrModel model = StarQrModel.model2,
  }) {
    StarPrntCommandWriter.writeQrCode(
      _writer,
      content: content,
      cellWidth: cellWidth,
      ecc: ecc.code,
      model: model.code,
    );
    return this;
  }

  /// Emits a complete binary raster image bounded by `ESC * r A` and `ESC * r B`.
  StarPrntPrinter raster({
    required Uint8List data,
    required int bytesPerRow,
    required int height,
  }) {
    StarPrntCommandWriter.writeRaster(
      _writer,
      data: data,
      bytesPerRow: bytesPerRow,
      height: height,
    );
    return this;
  }

  /// Emits a raster graphic from a [MonochromeBitmap].
  StarPrntPrinter rasterFromMonochrome(MonochromeBitmap bitmap) {
    return raster(
      data: bitmap.data,
      bytesPerRow: bitmap.bytesPerRow,
      height: bitmap.height,
    );
  }

  /// Emits `ESC * r A` — Enter Raster Mode.
  StarPrntPrinter enterRasterMode() {
    StarPrntCommandWriter.writeEnterRaster(_writer);
    return this;
  }

  /// Emits `b <nL> <nH> <rowData>` — Single Raster Row.
  StarPrntPrinter rasterRow(Uint8List rowData) {
    StarPrntCommandWriter.writeRasterRow(_writer, rowData);
    return this;
  }

  /// Emits `ESC * r B` — Exit Raster Mode.
  StarPrntPrinter exitRasterMode() {
    StarPrntCommandWriter.writeExitRaster(_writer);
    return this;
  }

  /// Appends raw binary bytes directly to the command stream without alteration.
  StarPrntPrinter rawBytes(Uint8List bytes) {
    StarPrntCommandWriter.writeRawBytes(_writer, bytes);
    return this;
  }

  /// Appends a raw ASCII command string directly to the command stream.
  StarPrntPrinter rawAscii(String command, {bool appendNewline = false}) {
    StarPrntCommandWriter.writeRawAscii(
      _writer,
      command,
      appendNewline: appendNewline,
    );
    return this;
  }

  /// Returns a snapshot of the current binary command stream as [Uint8List].
  ///
  /// This method is idempotent and does NOT reset, mutate, or auto-finalize the job.
  Uint8List toBytes() => _writer.toBytes();

  /// Clears all accumulated commands and restores encoding to constructor defaults.
  void reset() {
    _writer = PrinterByteWriter();
    _applyEncoding(_initialEncoding, emitCommand: false);
  }
}
